#!/usr/bin/env sh

if [ $# -eq 0 ]; then
    echo "Usage: $0 DIRECTORY"
    exit 1
fi

DIR="$1"
LOOKER="${DIR}/.lsinfo"

if [ ! -d "$DIR" ]; then
    echo "Directory $DIR does not exist"
    exit 1
fi

if [ -f "${LOOKER}" ]; then
    printf "Memo: "
    bat "${LOOKER}" && echo
fi
ls "$DIR"
