#!/usr/bin/env sh

if [ $# -eq 0 ]; then
    echo "Usage: $0 directory_name"
    exit 1
fi

if ! command -v bat &> /dev/null; then
    RUNNER="cat"
else
    RUNNER="bat --decorations never --language markdown"
fi

DIR="$1"
LOOKER="${DIR}/.lsinfo"

if [ ! -d "$DIR" ]; then
    echo "Error: directory '$DIR' does not exist"
    exit 1
fi

if [ -f "${LOOKER}" ]; then
    $RUNNER $LOOKER
    echo
fi
ls "$DIR"
